name: Update RSS Feed
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  update_rss:
    runs-on: ubuntu-latest
    steps:
      - uses: davesmes/github-readme-rss-action@v1
        with:
          feed-url: https://apartamentoscampolim.com.br
          file: BLOG.md
