name: Update Contribution Graph
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  update_activity:
    runs-on: ubuntu-latest
    steps:
      - uses: ashutosh00710/github-readme-activity-graph@main
        with:
          file: CONTRIBUTION.md
